### ISSUE TITLE
hexo-theme-next support

### ISSUE THREAD

**Issue by cloud-yu** [webappdevelp/hexo-filter-mermaid-diagrams#1]
hexo-theme-next用的swig模板，这个插件能在next主题上用么？

**Comment by Zhang21** [comment]
同问，+1

**Comment by david11rsww** [comment]
可以，对比一下配置文件，然后在footer.swig上可以用，需要参考一下next的swig语法。

**Comment by Zhang21** [comment]
@cloud-yu  开发者已在README上添加上NEXT的操作。

**Comment by Zhang21** [comment]
@webappdevelp 我按照README的方法对landscape和next两个主题都测试过，依然无法生效。

<br>

我已经安装了mermaid

**Comment by Orange168** [comment]
实测无效Next主题

**Comment by Orange168** [comment]
https://tyloafer.github.io/posts/7790/
以上教程也是无效，同一主题，安装方法一样

**Comment by ghost** [comment]
实测Next主题无效，何时才能修复？

**Comment by cloud-yu** [comment]
试过了，在Next主题 layout/_partials/footer.swig中按照guide中描述的方法可以正常显示。

**Comment by qzi** [comment]
Next 无效
